src/Entity/Relation.php
<?php 
namespace App\Entity;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use App\Entity\User;
use App\Entity\Page;

/** @MongoDB\EmbeddedDocument */
class Relation
{

    /** 
     * Reference the Page wich own (publicate) the News
     * @MongoDB\ReferenceOne(targetDocument="Page") 
     */
    private $parent;


    /** 
     * Reference the admins of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $admins;
    /**
     * @MongoDB\ReferenceMany(targetDocument="Page")
     */
    private $isAdminOf;
    /** 
     * Reference the admins of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $adminsRequests;


    /** 
     * Reference the friends of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $friends;
    /** 
     * Reference the friendsRequests of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $friendsRequests;


    /** 
     * Reference the followers of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $followers;
    /** 
     * Reference the follows of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $follows;


    /** 
     * Reference the participants of the Page (event)
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $participants;
    /** 
     * Reference the event Page where this Page participage
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $participateTo;


    
    /** 
     * Reference the likers of the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $likers;
    /** 
     * Reference the page liked by the Page
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $likes;

    /** 
     * Reference the Pages i am able to chat with
     * @MongoDB\ReferenceMany(targetDocument="Page") 
     */
    private $chatContacts;


    public function __construct($parent)
    {
        //save the parent Page to enable access to all attributes
        //exemple : $this->parent->getOwner();
        $this->parent = $parent;

        $this->friends = array();
        $this->friendsRequests = array();
        $this->admins = array();
        $this->adminsRequests = array();
        $this->isAdminOf = array();
        $this->followers = array();
        $this->follows = array();
        $this->participants = array();
        $this->participateTo = array();
        $this->likers = array();
        $this->likes = array();
        $this->chatContacts = array();
    }

    /****************************** ADMINS ******************************************/

    /**
     * get admin
     */
    public function getAdmins()
    {   
        return $this->admins;
    }

    /**
     * add admin
     */
    public function addAdmin(Page $page)
    {
        
        if(!$this->getIsAdmin($page->getSlug())){
            $this->admins[] = $page;
            //all admins are friends
            $this->addFriend($page);
            $page->getRelations()->addFriend($this->parent);
            return true;
        }
        else{
            return false;
        }
    }

    /**
     * add admin
     */
    public function addIsAdminOf(Page $page)
    {
        if(!$this->getImAdminOf($page->getSlug())){
            $this->isAdminOf[] = $page;
            //dd("true addIsAdminOf");
            return true;
        }
        else{
            //dd("false addIsAdminOf");
            return false;
        }
    }

    public function getIsAdminOf()
    {
        return $this->isAdminOf;
    }

    public function getImAdminOf($slug)
    {
        foreach ($this->isAdminOf as $key => $page) {
            if($page->getSlug() == $slug) return true;
        }
        return false;
    }
    public function getImAdminOfId($id)
    {
        foreach ($this->isAdminOf as $key => $page) {
            if($page->getId() == $id) return true;
        }
        return false;
    }
    public function getIsAdmin($slug)
    {
        foreach ($this->admins as $key => $page) {
            if($page->getSlug() == $slug) return true;
        }
        return false;
    }
    /* ############# REQUESTS ############# */

        /**
         * get adminsRequests
         */
        public function getAdminsRequests()
        {   
            return $this->adminsRequests;
        }

        /**
         * add AdminsRequests
         */
        public function addAdminRequest(Page $page)
        {
            //add admin if the Page is not already a admin
            //and if it is not the parent (you cant be admin with yourself)
            if(empty($this->adminsRequests) || !$this->adminsRequests->contains($page) && $page != $this->parent){
                $this->adminsRequests[] = $page;
                return true;
            }
            else{
                return false;
            }
        }

        /**
         * remove adminsRequests
         */
        public function removeAdminRequest(Page $page)
        {   
            $this->adminsRequests->removeElement($page);
        }


    /**
     * remove admins
     */
    public function removeAdmin(Page $page)
    {   
        $this->admins->removeElement($page);
    }

    /**
     * remove admins
     */
    public function removeIsAdminOf(Page $page)
    {   
        $this->isAdminOf->removeElement($page);
    }


    /****************************** FRIENDS ******************************************/


    /**
     * get friends : return all pages, no matter of his type
     */
    public function getFriends()
    {   
        return $this->friends;
    }


    /**
     * get friends : return only page with type Page::TYPE_USER
     */
    public function getRealFriends()
    {
        $friends = array();
        foreach ($this->friends as $key => $page) {
            if($page->getType() == Page::TYPE_USER) $friends[] = $page;
        }
        return $friends;
    }

    /**
     * add friends
     */
    public function addFriend(Page $page)
    {
        //add friend if the Page is not already a friend
        //and if it is not the parent (you cant be friend with yourself)
        //dump($page->getId()); dump($this->parent->getId());
        if(!$this->getImFriend($page->getSlug()) && $page != $this->parent){
            $this->friends[] = $page;
            $this->addChatContacts($page);
            return true;
        }
        else{
            return false;
        }
    }

    /**
     * remove friends
     */
    public function removeFriend(Page $page)
    {   
        $this->friends->removeElement($page);
    }

    public function getIsMemberOf()
    {
        $members = array();
        foreach ($this->friends as $key => $page) {
            if($page->getType() != Page::TYPE_USER) $members[] = $page;
        }
        return $members;
        //return $this->isMemberOf;
    }

    public function getImFriend($slug)
    {
        foreach ($this->friends as $key => $page) {
            if($page->getSlug() == $slug) return true;
        }
        return false;
    }

    public function getImMember($slug)
    {
        foreach ($this->friends as $key => $page) {
            if($page->getSlug() == $slug && $page->getType != Page::TYPE_USER) 
                return true;
        }
        return false;
    }
    
    public function getImFriendId($id)
    {
        foreach ($this->friends as $key => $page) {
            if($page->getId() == $id) return true;
        }
        return false;
    }

    /* ############# REQUESTS ############# */

        /**
         * get friendsRequests
         */
        public function getFriendsRequests()
        {   
            return $this->friendsRequests;
        }

        /**
         * add friendsRequest
         */
        public function addFriendRequest(Page $page)
        {
            //add friend if the Page is not already a friend
            //and if it is not the parent (you cant be friend with yourself)
            if(empty($this->friendsRequests) || !$this->friendsRequests->contains($page) && $page != $this->parent){
                $this->friendsRequests[] = $page;
                return true;
            }
            else{
                return false;
            }
        }

        /**
         * remove friendsRequests
         */
        public function removeFriendRequest(Page $page)
        {   
            $this->friendsRequests->removeElement($page);
        }


    /****************************** FOLLOWERS ****************************************/


    /**
     * get followers
     */
    public function getFollowers()
    {   
        return $this->followers;
    }

    /**
     * add followers
     */
    public function addFollower(Page $page)
    {
        //add follower if the Page is not already a follower
        //and if it is not the parent (you cant be follower of yourself)
        //dd($this->inFollowers($page->getSlug()));
        if(!$this->inFollowers($page->getSlug())){
            $this->followers[] = $page;
            return true;
        }
        else{
            return false;
        }
    }

    /**
     * remove followers
     */
    public function removeFollower(Page $page)
    {   
        $this->followers->removeElement($page);
    }

    /**
     * remove followers
     */
    public function removeFollow(Page $page)
    {   
        $this->follows->removeElement($page);
        return true;
    }

    /**
     * add follows
     */
    public function addFollows(Page $page)
    {
        if(!$this->inFollows($page->getSlug())){
            $this->follows[] = $page;
            return true;
        }
        else{
            return false;
        }
    }

    /**
     * get follows
     */
    public function getFollows()
    {   

src/Entity/User.php
<?php
// src/Entity/User.php
namespace App\Entity;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

//use Captcha\Bundle\CaptchaBundle\Validator\Constraints as CaptchaAssert;

/**
 * User class contain only minimal informations, needed for login.<br>
 * All other informations about Users are stocked in Page class 
 *
 * @MongoDB\Document(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{

	const ROLE_DEFAULT = 'ROLE_USER';
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

	/**
	 * Auto generated mongoID
     * @MongoDB\Id(strategy="auto")
     */
	private $id;

	/**
     * @MongoDB\Field(type="string")
     */
	private $username;

	/**
     * @MongoDB\Field(type="string")
     */
	private $password;

	/**
     * @MongoDB\Field(type="string")
     */
	private $email;

	/**
	 * By default : false<br>
	 * isActive = true after email validation
     * @MongoDB\Field(type="boolean")
     */
	private $isActive;

	
	/**
     * @MongoDB\Field(type="collection")
     */
	private $roles;

    
	/** @MongoDB\NotSaved */
    private $plainPassword;

	/**
     * @MongoDB\Field(type="date")
     */
    private $passwordRequestedAt;

    /**
     * @MongoDB\Field(type="string")
     */
    private $token;


	/**
	 * Date initialized when user register
	 * Set one time, never modified after initialization
     * @MongoDB\Field(type="date")
     */
    private $created;

    /**
     * @MongoDB\ReferenceMany(targetDocument="Page", mappedBy="owner")
     */
    private $pages;

    /**
	 * ImageProfil are not register in User data.<br>
	 * This attribute allow us to retrieve ImageProfil from the Page linked to the user<br>
	 * Only to display ImageProfil in TopMenu from app.user
    */
    private $imageProfil;

	/**
	 * By default : false<br>
	 * isActive = true after email validation
     * @MongoDB\Field(type="boolean")
     */
	private $isSuperAdmin;



	public function __construct()
	{
		$this->isActive = true;
		$this->roles = ['ROLE_USER'];
		$this->token = bin2hex(random_bytes(20)); // 20 chars //$this->chatToken;
		$this->created = new \Datetime();
	}
    
	/*
	 * Get id
	 */
	public function getId()
	{
		return $this->id;
	}

	public function getRealUsername()
	{
		return $this->username;
	}
	public function getUsername()
	{
		return $this->email;
	}

	public function setUsername($username)
	{
		$this->username = $username;
		return $this;
	}


	public function getPassword()
	{
		return $this->password;
	}

	public function setPassword($password)
	{
		$this->password = $password;
		return $this;
	}

	/*
	 * Get email
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/*
	 * Set email
	 */
	public function setEmail($email)
	{
		$this->email = $email;
		return $this;
	}

	/*
	 * Get isActive
	 */
	public function getIsActive()
	{
		return $this->isActive;
	}

	/*
	 * Set isActive
	 */
	public function setIsActive($isActive)
	{
		$this->isActive = $isActive;
		return $this;
	}

	public function getSalt()
	{
		// pas besoin de salt puisque nous allons utiliser bcrypt
		// attention si vous utilisez une méthode d'encodage différente !
		// il faudra décommenter les lignes concernant le salt, créer la propriété correspondante, et renvoyer sa valeur dans cette méthode
		return null;
	}

	// modifier la méthode getRoles
	public function getRoles()
	{
		return $this->roles; 
	}

	public function setRoles(array $roles)
	{
		if (!in_array('ROLE_USER', $roles))
		{
			$roles[] = 'ROLE_USER';
		}
		foreach ($roles as $role)
		{
			if(substr($role, 0, 5) !== 'ROLE_') {
				throw new InvalidArgumentException("Chaque rôle doit commencer par 'ROLE_'");
			}
		}
		$this->roles = $roles;
		return $this;
	} 

	public function eraseCredentials()
	{
	}

	/** @see \Serializable::serialize() */
	public function serialize()
	{
		return serialize(array(
			$this->id,
			$this->username,
			$this->password,
			$this->isActive,
			// voir remarques sur salt plus haut
			// $this->salt,
		));
	}

	/** @see \Serializable::unserialize() */
	public function unserialize($serialized)
	{
		list (
			$this->id,
			$this->username,
			$this->password,
			$this->isActive,
			// voir remarques sur salt plus haut
			// $this->salt
		) = unserialize($serialized);
	}

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }
 
    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

     /*
     * Get created
     */
    public function getCreated()
    {
        return $this->created;
    }

    /*
     * Set created
     */
    public function setCreated($created)
    {
        $this->created = $created;
        return $this;
    }

     /*
     * Get passwordRequestedAt
     */
    public function getPasswordRequestedAt()
    {
        return $this->passwordRequestedAt;
    }

    /*
     * Set passwordRequestedAt
     */
    public function setPasswordRequestedAt($passwordRequestedAt)
    {
        $this->passwordRequestedAt = $passwordRequestedAt;
        return $this;
    }

    /*
     * Get token
     */
    public function getToken()
    {
        return $this->token;
    }

    /*
     * Set token
     */
    public function setToken($token)
    {
        $this->token = $token;
        return $this;
    }


    /*
     * add page
     */
    public function addPage(Page $page)
    {
        $this->pages[] = $page;
    }

    /*
     * get page
     */
    public function getPages()
    {
    	return $this->pages;
    }

    /*
     * get the page related to this user
     */
    public function getMyUserPage()
    {
    	foreach ($this->pages as $key => $page) {
    		if($page->getType() == "user") return $page;
    	}
    }
    /*
     * get the position (coordinates) of the page related to this user
     */
    public function getMyPosition()
    {
    	$page = $this->getMyUserPage();
    	return @$page->getCoordinates() ? $page->getCoordinates() : false;
    }

    public function getImageProfil(){
    	$myPage = $this->getMyUserPage();
    	return $myPage->getImageProfil();
    }

    /*
     * Get isSuperAdmin
     */
    public function isSuperAdmin()
    {
        return isset($this->isSuperAdmin) ? $this->isSuperAdmin : false;
    }

    /*
     * Set isSuperAdmin
     */
    public function setIsSuperAdmin($isSuperAdmin)
    {
        $this->isSuperAdmin = $isSuperAdmin;
        return $this;
    }
    
 //    public function getCaptchaCode()
	// {
	//     return $this->captchaCode;
	// }

	// public function setCaptchaCode($captchaCode)
	// {
	//     $this->captchaCode = $captchaCode;
	// }
	
    /*
     * Anonymifaction instead of remove
     */
    public function anonymify()
    {
        $this->username="";
		$this->password="";
		$this->email="";
		$this->isActive=false;
		$this->plainPassword="";
		$this->token="";
		$this->isSuperAdmin=false;

        return $this;
    }


}

templates/page/sections/about.html.twig
{% trans_default_domain 'page' %}

<div class="col-12 col-sm-6">
	{{ include('page/blocks/dashboard-block-left.html.twig', {  "page" : page, 
											   					"dashboard" : "false",
											   					"allDesc": true }) }}
</div>

<div class="col-12 col-sm-6">
	{{ include('page/blocks/dashboard-block-right.html.twig', {  "page" : page, 
											   					"dashboard" : "false" }) }}
</div>

templates/page/sections/community.html.twig
{% trans_default_domain 'page' %}

<style>
.btn-control > i.fa-angle-right{
	margin-top: 0px;
	margin-left: 3px;
	display: block;
	font-size: 25px;
}
.btn-control > i.fa-angle-down{
	margin-top: 4px;
	display: block;
	font-size: 25px;
}
.birthday-author-name{
	text-overflow: ellipsis;
	white-space: nowrap;
	overflow: hidden;
	display: inline-block;
}
.ui-block-title{
	margin-bottom:15px;
}
.birthday-item .author-thumb {
    width: 45px;
    height: 45px;
    margin-right: 0px;
}
</style>
<script src="{{ asset('js/group.js') }}"></script>

<div class="app-group col-12 no-padding">
{% set empty = true %}
{% if page.isConfAuth("SHOW_GROUP", app.user.myUserPage) %}{% set empty = false %}
	{{ include("group/manage-group.html.twig", { "form" : form,
												 "page" : page }) }}
{% endif %}

{% if page.isConfAuth("SHOW_FRIENDS", app.user.myUserPage) %}{% set empty = false %}
	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="ui-block">
			<div class="ui-block-title">
				<div class="h5 title">
					<button class="btn btn-control bg-blue btn-toogle-row" data-row-id="friends">
						<i class="fa fa-angle-down"></i>
					</button> 
					<i class="fa fa-hand-peace-o padding-5"></i> 
					<a class="letter-dark btn-toogle-row" data-row-id="friends" href="javascript:">
						{% if page.type == "user" %}
							{% trans %}My friends{% endtrans %}
						{% else %}
							{% trans %}Our members{% endtrans %}
						{% endif %} 
						<span style="font-family:unset;">({{ page.relations.realFriends|length }})</span>
					</a>
				</div>
			</div>
			<div class="row col no-margin row-toggle community-friends" data-row-id="friends">
				{% if page.relations.realFriends is defined %}
					{% for aPage in page.relations.realFriends %}
						{{ include("page/blocks/page-block-community.html.twig", { "aPage" : aPage, 'type': 'friends', 'page': page }) }}
					{% endfor %}
				{% endif %}
			</div>
		</div>
	</div>
{% endif %}

{% if page.isConfAuth("SHOW_FOLLOWERS", app.user.myUserPage) %}{% set empty = false %}
	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="ui-block">
			<div class="ui-block-title">
				<div class="h5 title">
					<button class="btn btn-control bg-blue btn-toogle-row" data-row-id="followers">
						<i class="fa fa-angle-right"></i>
					</button> 
					<i class="fa fa-link padding-5"></i> 
					<a class="letter-dark btn-toogle-row" data-row-id="followers" href="javascript:">
						{% trans %}Followers{% endtrans %} ({{ page.relations.followers|length }})
					</a>
				</div>
			</div>
			<div class="row col no-margin row-toggle" data-row-id="followers">
				{% if page.relations.followers is defined %}
					{% for aPage in page.relations.followers %}
						{{ include("page/blocks/page-block-community.html.twig", { "aPage" : aPage }) }}
					{% endfor %}
				{% endif %}
			</div>
		</div>
	</div>
{% endif %}

{% if page.type == "user" %}
	{% if page.isConfAuth("SHOW_FOLLOWS", app.user.myUserPage) %}{% set empty = false %}
		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="ui-block">
				<div class="ui-block-title">
					<div class="h5 title">
						<button class="btn btn-control bg-blue btn-toogle-row" data-row-id="follows">
							<i class="fa fa-angle-right"></i>
						</button> 
						<i class="fa fa-link padding-5"></i> 
						<a class="letter-dark btn-toogle-row" data-row-id="follows" href="javascript:">
							{% trans %}Follows{% endtrans %} ({{ page.relations.follows|length }})
						</a>
					</div>
				</div>
				<div class="row col no-margin row-toggle d-none" data-row-id="follows">
					{% if page.relations.follows is defined %}
						{% for aPage in page.relations.follows %}
							{{ include("page/blocks/page-block-community.html.twig", { "aPage" : aPage }) }}
						{% endfor %}
					{% endif %}
				</div>
			</div>
		</div>
	{% endif %}
{% endif %}

{% if page.type == "user" %}
	{% if page.isConfAuth("SHOW_MEMBEROF", app.user.myUserPage) %}{% set empty = false %}
		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="ui-block">
				<div class="ui-block-title">
					<div class="h5 title">
						<button class="btn btn-control bg-blue btn-toogle-row" data-row-id="memberof">
							<i class="fa fa-angle-right"></i>
						</button> 
						<i class="fa fa-link padding-5"></i> 
							<a class="letter-dark btn-toogle-row" data-row-id="memberof" href="javascript:">
								{% trans %}Member of{% endtrans %} ({{ page.relations.isMemberOf|length }})
							</a>
					</div>
				</div>
				<div class="row col no-margin row-toggle d-none" data-row-id="memberof">
					{% if page.relations.isMemberOf is defined %}
						{% for aPage in page.relations.isMemberOf %}
							{{ include("page/blocks/page-block-community.html.twig", { "aPage" : aPage }) }}
						{% endfor %}
					{% endif %}
				</div>
			</div>
		</div>
	{% endif %}
{% endif %}

{% if page.type == "user" %}
	{% if page.isConfAuth("SHOW_ADMINOF", app.user.myUserPage) %}{% set empty = false %}
		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="ui-block">
				<div class="ui-block-title">
					<div class="h5 title">
						<button class="btn btn-control bg-blue btn-toogle-row" data-row-id="adminof">
							<i class="fa fa-angle-right"></i>
						</button> 
						<i class="fa fa-link padding-5"></i> 
							<a class="letter-dark btn-toogle-row" data-row-id="adminof" href="javascript:">
								{% trans %}Admin of{% endtrans %} ({{ page.relations.isAdminOf|length }})
							</a>
					</div>
				</div>
				<div class="row col no-margin row-toggle d-none" data-row-id="adminof">
					{% if page.relations.isAdminOf is defined %}
						{% for aPage in page.relations.isAdminOf %}
							{{ include("page/blocks/page-block-community.html.twig", { "aPage" : aPage }) }}
						{% endfor %}
					{% endif %}
				</div>
			</div>
		</div>
	{% endif %}
{% endif %}

{% if page.type != "user" %}
	{% if page.isConfAuth("SHOW_ADMINS", app.user.myUserPage) %}{% set empty = false %}
		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="ui-block">
				<div class="ui-block-title">
					<div class="h5 title">
						<button class="btn btn-control bg-blue btn-toogle-row" data-row-id="admins">
							<i class="fa fa-angle-right"></i>
						</button> 
						<i class="fa fa-link padding-5"></i> 
						<a class="letter-dark btn-toogle-row" data-row-id="admins" href="javascript:">
							{% trans %}Admins{% endtrans %} ({{ page.relations.admins|length }})
						</a>
					</div>
				</div>
				<div class="row col no-margin row-toggle d-none" data-row-id="admins">
					{% if page.relations.admins is defined %}
						{% for aPage in page.relations.admins %}
							{{ include("page/blocks/page-block-community.html.twig", { "aPage" : aPage }) }}
						{% endfor %}
					{% endif %}
				</div>
			</div>
		</div>
	{% endif %}
{% endif %}

{% set len = (page.owner.pages|length) - 1 %}

{% if page.type == "user" %}
	{% if page.isConfAuth("SHOW_PAGECREATED", app.user.myUserPage) %}{% set empty = false %}
		<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="ui-block">
				<div class="ui-block-title">
					<div class="h5 title">
						<button class="btn btn-control bg-blue btn-toogle-row" data-row-id="mypages">
							<i class="fa fa-angle-right"></i>
						</button> 
						<i class="fa fa-newspaper-o padding-5"></i> 
						<a class="letter-dark btn-toogle-row" data-row-id="mypages" href="javascript:">
							{% transchoice len %}[0,1] My page|[2,Inf[ My pages{% endtranschoice %} ({{ len }})
						</a>
					</div>
				</div>
				<div class="row col no-margin row-toggle d-none" data-row-id="mypages">
					{% for aPage in page.owner.pages %}
						{% if aPage.id != page.id %}
							{{ include("page/blocks/page-block-community.html.twig", { "aPage" : aPage }) }}
						{% endif %}
					{% endfor %}
				</div>
			</div>
		</div>
	{% endif %}
{% endif %}


{% if empty == true %}
	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="ui-block">
			<div class="ui-block-title">
				<div class="h5 title">
					<i class="fa fa-ban padding-5"></i> 
					<a class="letter-dark btn-toogle-row" data-row-id="mypages" href="javascript:">
						{% trans %}The privacy settings on this page do not allow you to view the community on this page.{% endtrans %}
					</a>
				</div>
			</div>
			
		</div>
	</div>
{% endif %}

</div>

<script>
    $( document ).ready(function() {
		group.initUi();
		nexxo.initBtnRequest();
    });
</script>

templates/page/sections/delete-page.html.twig
{% trans_default_domain 'page' %}

<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-xs-12">
	<div class="ui-block">
		<div class="ui-block-title">
			<h5 class="title">
				<i class="fa fa-trash"></i> 
				{% if page.type == "user" %}
					{% trans %}Delete my account{% endtrans %}
				{% else %}
					{% trans %}Delete this page{% endtrans %}
				{% endif %}
			</h5>
		</div>
		<div class="row col no-margin padding-15">
			{% if page.type == "user" %}
				<p>
					{% trans %}Deleting your account will result in automatic and permanent deletion of all the content you have published{% endtrans %}.
					<br>
					{% trans %}Will be deleted: messages, comments, notifications, as well as pages of which you are the only administrator
					{% endtrans %}.
					<br>
					({% trans %}If you are not the only administrator of a page, you will only be removed from the list of administrators, and the page will continue to exist{% endtrans %})
				</p><hr>
			{% else %}
				<p>
					{% trans %}Deleting this page will result in automatic and permanent deletion all contents published by this page, or linked to this page{% endtrans %}.
						<br>
					{% trans %}Will be deleted: messages, comments, notifications, as well as pages of which{% endtrans %}
					<b>{{ page.name }}</b> 
					{% trans %}is the owner{% endtrans %}.
				</p><hr>
			{% endif %}

		</div>
		<div class="row col no-margin row-toggle padding-15">
				<a href="{{ path('page', {'slug' : page.slug })}}" class="btn btn-secondary">
					{% trans %}Cancel{% endtrans %}
				</a> 
				{% if page.type == "user" %}
					<a href="{{ path('remove-page', { 'slug' : page.slug }) }}" class="btn bg-red margin-left-15">
						<i class="fa fa-trash"></i> 
						{% trans %}Delete my account{% endtrans %}
					</a>
				{% else %}
					<a href="{{ path('remove-page', { 'slug' : page.slug }) }}" class="btn bg-red margin-left-15">
						<i class="fa fa-trash"></i> 
						{% trans %}Delete this page{% endtrans %}
					</a>
				{% endif %}
		</div>
	</div>
</div>

templates/page/sections/main.html.twig
{% trans_default_domain 'page' %}


<!-- Main Content -->

<div class="col-xl-6 order-xl-2 col-lg-12 order-lg-1 col-md-12 col-sm-12 col-xs-12" id="stream-container">
	{{ include('news/news-stream.html.twig', { "page" : page, 
											   "dashboard" : "false" }) }}
</div>

<!-- ... end Main Content -->

<!-- Left Sidebar -->

<div class="col-xl-3 order-xl-1 col-lg-6 order-lg-2 col-md-6 col-sm-12 col-xs-12">
	{{ include('page/blocks/dashboard-block-left.html.twig', {  "page" : page, 
											   					"dashboard" : "false" }) }}
</div>

<!-- ... end Left Sidebar -->


<!-- Right Sidebar -->

<div class="col-xl-3 order-xl-3 col-lg-6 order-lg-3 col-md-6 col-sm-12 col-xs-12">

	{{ include('page/blocks/dashboard-block-right.html.twig', {  "page" : page, 
											   					"dashboard" : "false" }) }}

</div>

<!-- ... end Right Sidebar -->