src/Entity/User.php
<?php
// src/Entity/User.php
namespace App\Entity;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

//use Captcha\Bundle\CaptchaBundle\Validator\Constraints as CaptchaAssert;

/**
 * User class contain only minimal informations, needed for login.<br>
 * All other informations about Users are stocked in Page class 
 *
 * @MongoDB\Document(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{

	const ROLE_DEFAULT = 'ROLE_USER';
    const ROLE_SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

	/**
	 * Auto generated mongoID
     * @MongoDB\Id(strategy="auto")
     */
	private $id;

	/**
     * @MongoDB\Field(type="string")
     */
	private $username;

	/**
     * @MongoDB\Field(type="string")
     */
	private $password;

	/**
     * @MongoDB\Field(type="string")
     */
	private $email;

	/**
	 * By default : false<br>
	 * isActive = true after email validation
     * @MongoDB\Field(type="boolean")
     */
	private $isActive;

	
	/**
     * @MongoDB\Field(type="collection")
     */
	private $roles;

    
	/** @MongoDB\NotSaved */
    private $plainPassword;

	/**
     * @MongoDB\Field(type="date")
     */
    private $passwordRequestedAt;

    /**
     * @MongoDB\Field(type="string")
     */
    private $token;


	/**
	 * Date initialized when user register
	 * Set one time, never modified after initialization
     * @MongoDB\Field(type="date")
     */
    private $created;

    /**
     * @MongoDB\ReferenceMany(targetDocument="Page", mappedBy="owner")
     */
    private $pages;

    /**
	 * ImageProfil are not register in User data.<br>
	 * This attribute allow us to retrieve ImageProfil from the Page linked to the user<br>
	 * Only to display ImageProfil in TopMenu from app.user
    */
    private $imageProfil;

	/**
	 * By default : false<br>
	 * isActive = true after email validation
     * @MongoDB\Field(type="boolean")
     */
	private $isSuperAdmin;



	public function __construct()
	{
		$this->isActive = true;
		$this->roles = ['ROLE_USER'];
		$this->token = bin2hex(random_bytes(20)); // 20 chars //$this->chatToken;
		$this->created = new \Datetime();
	}
    
	/*
	 * Get id
	 */
	public function getId()
	{
		return $this->id;
	}

	public function getRealUsername()
	{
		return $this->username;
	}
	public function getUsername()
	{
		return $this->email;
	}

	public function setUsername($username)
	{
		$this->username = $username;
		return $this;
	}


	public function getPassword()
	{
		return $this->password;
	}

	public function setPassword($password)
	{
		$this->password = $password;
		return $this;
	}

	/*
	 * Get email
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/*
	 * Set email
	 */
	public function setEmail($email)
	{
		$this->email = $email;
		return $this;
	}

	/*
	 * Get isActive
	 */
	public function getIsActive()
	{
		return $this->isActive;
	}

	/*
	 * Set isActive
	 */
	public function setIsActive($isActive)
	{
		$this->isActive = $isActive;
		return $this;
	}

	public function getSalt()
	{
		// pas besoin de salt puisque nous allons utiliser bcrypt
		// attention si vous utilisez une méthode d'encodage différente !
		// il faudra décommenter les lignes concernant le salt, créer la propriété correspondante, et renvoyer sa valeur dans cette méthode
		return null;
	}

	// modifier la méthode getRoles
	public function getRoles()
	{
		return $this->roles; 
	}

	public function setRoles(array $roles)
	{
		if (!in_array('ROLE_USER', $roles))
		{
			$roles[] = 'ROLE_USER';
		}
		foreach ($roles as $role)
		{
			if(substr($role, 0, 5) !== 'ROLE_') {
				throw new InvalidArgumentException("Chaque rôle doit commencer par 'ROLE_'");
			}
		}
		$this->roles = $roles;
		return $this;
	} 

	public function eraseCredentials()
	{
	}

	/** @see \Serializable::serialize() */
	public function serialize()
	{
		return serialize(array(
			$this->id,
			$this->username,
			$this->password,
			$this->isActive,
			// voir remarques sur salt plus haut
			// $this->salt,
		));
	}

	/** @see \Serializable::unserialize() */
	public function unserialize($serialized)
	{
		list (
			$this->id,
			$this->username,
			$this->password,
			$this->isActive,
			// voir remarques sur salt plus haut
			// $this->salt
		) = unserialize($serialized);
	}

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }
 
    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

     /*
     * Get created
     */
    public function getCreated()
    {
        return $this->created;
    }

    /*
     * Set created
     */
    public function setCreated($created)
    {
        $this->created = $created;
        return $this;
    }

     /*
     * Get passwordRequestedAt
     */
    public function getPasswordRequestedAt()
    {
        return $this->passwordRequestedAt;
    }

    /*
     * Set passwordRequestedAt
     */
    public function setPasswordRequestedAt($passwordRequestedAt)
    {
        $this->passwordRequestedAt = $passwordRequestedAt;
        return $this;
    }

    /*
     * Get token
     */
    public function getToken()
    {
        return $this->token;
    }

    /*
     * Set token
     */
    public function setToken($token)
    {
        $this->token = $token;
        return $this;
    }


    /*
     * add page
     */
    public function addPage(Page $page)
    {
        $this->pages[] = $page;
    }

    /*
     * get page
     */
    public function getPages()
    {
    	return $this->pages;
    }

    /*
     * get the page related to this user
     */
    public function getMyUserPage()
    {
    	foreach ($this->pages as $key => $page) {
    		if($page->getType() == "user") return $page;
    	}
    }
    /*
     * get the position (coordinates) of the page related to this user
     */
    public function getMyPosition()
    {
    	$page = $this->getMyUserPage();
    	return @$page->getCoordinates() ? $page->getCoordinates() : false;
    }

    public function getImageProfil(){
    	$myPage = $this->getMyUserPage();
    	return $myPage->getImageProfil();
    }

    /*
     * Get isSuperAdmin
     */
    public function isSuperAdmin()
    {
        return isset($this->isSuperAdmin) ? $this->isSuperAdmin : false;
    }

    /*
     * Set isSuperAdmin
     */
    public function setIsSuperAdmin($isSuperAdmin)
    {
        $this->isSuperAdmin = $isSuperAdmin;
        return $this;
    }
    
 //    public function getCaptchaCode()
	// {
	//     return $this->captchaCode;
	// }

	// public function setCaptchaCode($captchaCode)
	// {
	//     $this->captchaCode = $captchaCode;
	// }
	
    /*
     * Anonymifaction instead of remove
     */
    public function anonymify()
    {
        $this->username="";
		$this->password="";
		$this->email="";
		$this->isActive=false;
		$this->plainPassword="";
		$this->token="";
		$this->isSuperAdmin=false;

        return $this;
    }


}

templates/theme/admin.html.twig
{% trans_default_domain 'theme' %}

{% extends('base.html.twig') %}

{% block body %}
    <p class="text-center">Bienvenue dans l'espace admin</p>
    
{% endblock %}

templates/theme/base-app.html.twig
{% trans_default_domain 'theme' %}

<!DOCTYPE html>
<html>
    <head>
        {% block metadata %}
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

            <meta charset="UTF-8" />
            <meta property="og:url"                content="{{ base_url }}" />
            <meta property="og:type"               content="application" />
            <meta property="og:title"              content="Nexxo" />
            <meta property="og:description"        content="Reseau social pour un autre monde" />
            <meta property="og:image"              content="{{ base_url }}/img/landscape/space-msg-2-medium.png" />

            <meta name="keywords" content="social network, réseau social"/>

            <meta name="description" content="Réseau social pour demain | Nexxo est un espace de communication unique, pour toutes celles et ceux qui souhaitent se relier aux autres localement, dans la volonté de discuter des problèmes de notre époque, trouver des solutions, et coordonner les initiatives dans tous les domaines, pour construire ensemble un avenir serein pour nous-même et pour nos enfants."/>
        {% endblock %}

        
        {% block title %}
            <title data-title="Nexxo" data-count="0">
                Nexxo
            </title>
        {% endblock %}

        {% block stylesheets %}
             {{ include('theme/stylesheets.html.twig') }}
        {% endblock %}
        
        {% block favicon %}
             {{ include('theme/favicon.html.twig') }}
        {% endblock %}
        
        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
    </head>
    <body class="{% if app.user.myUserPage.isPrefAuth('USE_DARK_THEME') == "true" %}dark-theme{% endif %}">
        {% block sideBarLeft %}
            {{ include('theme/side-bar-left.html.twig') }}
        {% endblock %}

        {% block sideBarRight %}
            {{ include('theme/side-bar-right.html.twig') }}
        {% endblock %}

        {% block menuTop %}
            {{ include('theme/menu-top.html.twig') }}
        {% endblock %}

        {% block body %}{% endblock %}

        {% block tchat %}
            {{ include('theme/tchat.html.twig') }}
        {% endblock %}

        {% block quickView %}
            {{ include('theme/modal-quickview.html.twig') }}
        {% endblock %}

        {% block javascripts %}
             {{ include('theme/javascripts.html.twig') }}
        {% endblock %}

        <div id="sig-assets"></div>

        <audio id="sound-message" src="{{ asset('sound/sound-message.mp3') }}" type="audio/mp3">
        <audio id="sound-notification" src="{{ asset('sound/sound-notification.wav') }}" type="audio/wav">
    </body>
</html>

templates/theme/base-landing.html.twig
<!DOCTYPE html>
<html>
    <head>
        {% block metadata %}
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

            <meta charset="UTF-8" />
            <meta property="og:url"                content="{{ base_url }}" />
            <meta property="og:type"               content="application" />
            <meta property="og:title"              content="Nexxo" />
            <meta property="og:description"        content="Reseau social pour un autre monde" />
            <meta property="og:image"              content="{{ base_url }}/img/landscape/space-msg-2-medium.png" />

            <meta name="keywords" content="social network, réseau social"/>

            <meta name="description" content="Réseau social pour un autre monde | Nexxo est un espace de communication unique, au service de ceux qui souhaitent se relier aux autres localement, dans la volonté de discuter des problèmes de notre époque, trouver des solutions, et coordonner les initiatives dans tous les domaines, pour construire ensemble un avenir serein pour nous-même et pour nos enfants."/>

        {% endblock %}
        
        {% block title %}
            <title data-title="Nexxo" data-count="0">Nexxo</title>
        {% endblock %}
        
        {% block stylesheets %}
            {{ include('theme/stylesheets.html.twig') }}
            <link rel="stylesheet" href="{{ asset('css/landing.css') }}" />
        {% endblock %}
        
        {% block favicon %}
             {{ include('theme/favicon.html.twig') }}
        {% endblock %}

        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
    </head>
    <body class="dark-theme landing-page">

        {% block background %}
            <div class="content-bg-wrap">
                <div class="content-bg"></div>
            </div>
        {% endblock %}
        

        {{ include('theme/landing/menu-top.html.twig') }}
        
        {% block flash %}
            {{include('theme/flash.html.twig')}} 
        {% endblock %}
        
        {% block javascripts %}
             {{ include('theme/javascripts.html.twig') }}
        {% endblock %}

        {% block body %}{% endblock %}

        {% block footer %}
             {{ include('theme/footer.html.twig') }}
        {% endblock %}
        
        {% block quickView %}
            {{ include('theme/modal-quickview.html.twig') }}
        {% endblock %}

    </body>
</html>

templates/theme/base-map-embed.html.twig
{% trans_default_domain 'theme' %}

<!DOCTYPE html>
<html>
    <head>
        {% block metadata %}
            <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

            <meta charset="UTF-8" />
            <meta property="og:url"                content="{{ base_url }}" />
            <meta property="og:type"               content="application" />
            <meta property="og:title"              content="Nexxo" />
            <meta property="og:description"        content="Reseau social pour un autre monde" />
            <meta property="og:image"              content="{{ base_url }}/img/landscape/space-msg-2-medium.png" />

            <meta name="keywords" content="social network, réseau social"/>

            <meta name="description" content="Réseau social pour demain | Nexxo est un espace de communication unique, pour toutes celles et ceux qui souhaitent se relier aux autres localement, dans la volonté de discuter des problèmes de notre époque, trouver des solutions, et coordonner les initiatives dans tous les domaines, pour construire ensemble un avenir serein pour nous-même et pour nos enfants."/>
        {% endblock %}

        
        {% block title %}
            <title data-title="Nexxo" data-count="0">
                Nexxo
            </title>
        {% endblock %}

        {% block stylesheets %}
             {{ include('theme/stylesheets.html.twig') }}
        {% endblock %}
        
        {% block favicon %}
             {{ include('theme/favicon.html.twig') }}
        {% endblock %}
        
        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
    </head>
    <body class="{% if app.user.myUserPage.isPrefAuth('USE_DARK_THEME') == "true" %}dark-theme{% endif %}">
        
        {% block body %}{% endblock %}

        {% block javascripts %}
             {{ include('theme/javascripts.html.twig') }}
        {% endblock %}

        <div id="sig-assets"></div>

    </body>
</html>

templates/theme/favicon.html.twig
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

templates/theme/modal-quickview.html.twig
<div class="modal fade" id="modal-quickview" tabindex="-1" role="dialog" aria-labelledby="modal-quickview" aria-hidden="true">
  <div class="modal-dialog ui-block window-popup modal-quickview" role="document">
    <div class="modal-content" id="modal-content">
      
    </div>
  </div>
</div>

templates/theme/side-bar-right.html.twig
{% trans_default_domain 'theme' %}

<!-- Fixed Sidebar Right -->

<div class="fixed-sidebar right">
	<div class="fixed-sidebar-right sidebar--small" id="sidebar-right">

		<div class="mCustomScrollbar" data-mcs-theme="dark">
			<ul class="chat-users">
			{% for friend in app.user.myUserPage.relations.chatContacts %}
   				<li class="inline-items js-chat-open" data-slug="{{ friend.slug }}" 
   					{% if friend.informations.discord != "" and friend.isConfAuth("SHOW_INFO_DISCORD", app.user.myUserPage) %}
   						data-discord="{{ friend.informations.discord }}" 
   					{% endif %}
   					data-name="{{ friend.name }}" data-type="{{ friend.type }}"
   					data-thumb="{{ friend.imageProfil }}" data-status="">
					<div class="author-thumb margin-right-15" data-toggle="tooltip" data-original-title="{{ friend.name }}" data-placement="left">
						<img src="{{ asset('uploads/imgProfil/' ~ friend.imageProfil) }}" alt="image" height="42">
						<span class="icon-status {{ friend.chatStatus }}"></span>
						<span class="count-toread-msg badge d-none" data-count="0">0</span>
					</div>
				</li>
			{% endfor %}

			</ul>
		</div>

		<div class="search-friend inline-items padding-5" 
			 style="bottom:77px;background:rgba(38, 37, 37, 0.6);text-align:center;">
			<div class="lbl-socket-connected" title="">
				<i class="fa fa-plug"></i>
			</div>

		</div>
		<div class="search-friend inline-items">
			<div class="js-sidebar-open">
				<i class="fa fa-bars fa-2x"></i>
			</div>

		</div>

	</div>

	<div class="fixed-sidebar-right sidebar--large" id="sidebar-right-1">

		<div class="mCustomScrollbar" data-mcs-theme="dark">
			<ul class="chat-users">
				{% for friend in app.user.myUserPage.relations.chatContacts %}
	   				<li class="inline-items js-chat-open" data-slug="{{ friend.slug }}" 
	   					{% if friend.informations.discord != "" and friend.isConfAuth("SHOW_INFO_DISCORD", app.user.myUserPage) %}
	   						data-discord="{{ friend.informations.discord }}" 
	   					{% endif %}
	   					data-name="{{ friend.name }}" data-type="{{ friend.type }}"
	   					data-thumb="{{ friend.imageProfil }}" data-status="">
						<div class="author-thumb">
							<img src="{{ asset('uploads/imgProfil/' ~ friend.imageProfil) }}" alt="image" height="42">
							<span class="icon-status"></span>
							<span class="count-toread-msg badge d-none" data-count="0">0</span>
						</div>
						<div class="author-status">
							<span class="h6 author-name">{{ friend.name }}</span>
							{% if friend.city != "" and friend.isConfAuth("SHOW_ADDRESS", app.user.myUserPage) %}
								<br><span><i class="fa fa-map-marker"></i> {{ friend.city }}</span>
							{% endif %}
						</div>
					</li>
				{% endfor %}
				
				{% if app.user.myUserPage.relations.chatContacts|length == 0 %}
					<li class="inline-items js-chat-open"><br>
						<h5><i class="fa fa-comments"></i> {% trans %}Private messaging{% endtrans %}</h5>
						<p>
							{% trans %}Your contact list is empty{% endtrans %}.<br>
						</p>
					</li>
				{% endif %}
				
			</ul>
		</div>

		<div class="search-friend inline-items">
			<form class="form-group">
				<input class="form-control" id="search-friend-chat" 
					   placeholder="{% trans %}Search contact{% endtrans %}..." value="" type="text">
			</form>

			<div class="js-sidebar-open">
				{# <svg class="olymp-close-icon"><use xlink:href="{{ asset('icons/icons.svg') }}#olymp-close-icon"></use></svg> #}
				<i class="fa fa-times fa-2x"></i>
			</div>
		</div>

	</div>
</div>

<!-- ... end Fixed Sidebar Right -->

<!-- Fixed Sidebar Right -->
{# 
<div class="fixed-sidebar right fixed-sidebar-responsive">

	<div class="fixed-sidebar-right sidebar--small" id="sidebar-right-responsive">

		<a href="#" class="olympus-chat inline-items js-chat-open">
			<svg class="olymp-chat---messages-icon"><use xlink:href="{{ asset('icons/icons.svg') }}#olymp-chat---messages-icon"></use></svg>
		</a>

	</div>

</div> #}

<!-- ... end Fixed Sidebar Right -->

templates/theme/tchat.html.twig
{% trans_default_domain 'theme' %}
<style>
#lbl-sending-chat-msg{
	position: absolute;
	bottom: 100px;
	left: 10%;
	width: 80%;
	border-radius: 20px;
	background-color: rgb(41, 51, 57);
	padding: 14px;
}
</style>
<!-- Window-popup-CHAT for responsive min-width: 768px -->
<div class="ui-block popup-chat popup-chat-responsive">
	<div class="ui-block-title">
		<span class="icon-status online"></span>
		<div class="title" style="max-width: 280px;"></div>
		<div class="more no-margin">
			<i class="fa fa-circle-o-notch transparent" id="icon-loading-chat" style=""></i>
			<a href="javascript:" class="js-chat-maximize">
				<i class="fa fa-arrows-h fa-2x letter-white"></i>
			</a>
			<a href="javascript:" class="js-chat-close">
				<i class="fa fa-times fa-2x letter-white"></i>
			</a>
		</div>
	</div>
	<div class="mCustomScrollbar">
		<a href="javascript:" class="load-before-conv">
			<i class="fa fa-arrow-up "></i> {% trans %}Load old messages{% endtrans %}
		</a>
		<ul class="notification-list chat-message chat-message-field">
		</ul>
	</div>

	<div class="padding-10 text-center d-none" id="lbl-sending-chat-msg">
		<i class="fa fa-spin fa-circle-o-notch"></i> {% trans %}Sending message{% endtrans %}
	</div>

	<form class="form-chat">
		<div class="form-group label-floating is-empty">
			<label class="control-label">{% trans %}Your message{% endtrans %}...</label>
			<textarea class="form-control chat-msg" placeholder="" 
					data-username-sender="{{ app.user.myUserPage.name }}"
					data-slug-receiver="" data-type-receiver=""></textarea>
		</div>
	</form>
</div>

templates/theme/user-menu.html.twig
{% trans_default_domain 'theme' %}

<div class="author-page author vcard inline-items more">
	<div class="author-thumb">
		<a href="{{ path('my-page') }}">
			<img src="{{ asset('uploads/imgProfil/' ~ app.user.imageProfil) }}" height="40"/>
		</a>

		<span class="icon-status menu-top {{ app.user.myUserPage.chatStatus }}" 
			  data-slug="{{ app.user.myUserPage.slug }}"></span>

		<div class="more-dropdown more-with-triangle user-menu">
			<div class="mCustomScrollbar" data-mcs-theme="dark">
				<div class="ui-block-title ui-block-title-small">
					<h6 class="title">{% trans %}Your Account{% endtrans %}</h6>
				</div>

				<ul class="account-settings">
					{% if app.user.myUserPage.firstStep == 0 %}
					<li>
						<a href="{{ path('page-settings', {'slug' : app.user.myUserPage.slug, 'subview': 'form-confidentiality' }) }}">
							{# <svg class="olymp-settings-icon">
							<use xlink:href="{{ asset('icons/icons.svg') }}#olymp-settings-icon"></use>
							</svg> #}
							<i class="fa fa-cogs fa-2x margin-right-15"></i>
							<span>{% trans %}Settings{% endtrans %}</span>
						</a>
					</li>
					{% endif %}
					{% if app.user.isSuperAdmin %}
					<li>
						<a href="{{ path('superadmin') }}">
							{# <svg class="olymp-star-icon left-menu-icon"  data-toggle="tooltip" data-placement="right" 
								data-original-title="FAV PAGE">
								<use xlink:href="{{ asset('icons/icons.svg') }}#olymp-star-icon"></use>
							</svg> #}
							<i class="fa fa-user-secret fa-2x margin-right-15"></i>
							<span>{% trans %}Super-Admin{% endtrans %}</span>
						</a>
					</li>
					{% endif %}
					<li>
						<a href="/">
							{# <svg class="olymp-logout-icon"><use xlink:href="{{ asset('icons/icons.svg') }}#olymp-logout-icon"></use></svg> #}
							<i class="fa fa-home fa-2x margin-right-15"></i>
							<span>{% trans %}Home page{% endtrans %}</span>
						</a>
					</li>
					<li>
						<a href="/logout">
							{# <svg class="olymp-logout-icon"><use xlink:href="{{ asset('icons/icons.svg') }}#olymp-logout-icon"></use></svg> #}
							<i class="fa fa-sign-out fa-2x margin-right-15"></i>
							<span>{% trans %}Log Out{% endtrans %}</span>
						</a>
					</li>
				</ul>

				{# <div class="ui-block-title ui-block-title-small">
					<h6 class="title">{% trans %}Moderation{% endtrans %}</h6>
				</div>

				<ul>
					<li>
						<a href="{{ path('all-reports-pages') }}">
							<span>
								<i class="fa fa-balance-scale"></i> 
								{% trans %}Collective moderation{% endtrans %}
							</span>
						</a>
					</li>
				</ul> #}

				{% if app.user.myUserPage.firstStep == 0 %}
				<div class="ui-block-title ui-block-title-small">
					<h6 class="title">{% trans %}Chat Settings{% endtrans %}</h6>
				</div>

				<ul class="chat-settings">
					<li class="btn-change-chat-status" data-status="online">
						<a href="javascript:">
							<span class="icon-status online"></span>
							<span>{% trans %}Online{% endtrans %}</span>
						</a>
					</li>
					<li class="btn-change-chat-status" data-status="away">
						<a href="javascript:">
							<span class="icon-status away"></span>
							<span>{% trans %}Away{% endtrans %}</span>
						</a>
					</li>
					<li class="btn-change-chat-status" data-status="offline">
						<a href="javascript:">
							<span class="icon-status disconected"></span>
							<span>{% trans %}Offline{% endtrans %}</span>
						</a>
					</li>
				</ul>
				{% endif %}


				<div class="ui-block-title ui-block-title-small">
					<h6 class="title">{% trans %}More{% endtrans %}</h6>
				</div>

				<ul>
					<li>
						<a href="{{ path('all-reports-pages') }}">
							<span>
								<i class="fa fa-balance-scale"></i> 
								{% trans %}Collective moderation{% endtrans %}
							</span>
						</a>
					</li>
					<li>
						<a href="{{ path('contact-admin', { 'type' : 'bug' }) }}">
							<span>
								<i class="fa fa-bug"></i> 
								{% trans %}Report bug{% endtrans %}
							</span>
						</a>
					</li>
					<li>
						<a href="{{ path('contact-admin', { 'type' : 'suggestion' }) }}">
							<span>
								<i class="fa fa-comment"></i> 
								{% trans %}Send suggestion{% endtrans %}
							</span>
						</a>
					</li>
					<li>
						<a href="{{ path('contact-admin', { 'type' : 'message' }) }}">
							<span>
								<i class="fa fa-envelope"></i> 
								{% trans %}Contact{% endtrans %}
							</span>
						</a>
					</li>
				</ul>
			</div>

		</div>
	</div>
	<a href="{{ path('my-page') }}" class="author-name fn" style="max-width:140px;margin-top: 2px;">
		<div class="author-title" style="max-width:140px;">
			<span class="elipsis" style="max-width:110px;">
				{{ app.user.realUsername }}
			</span>
			{# <svg class="olymp-dropdown-arrow-icon">
				<use xlink:href="{{ asset('icons/icons.svg') }}#olymp-dropdown-arrow-icon"></use>
			</svg> #}
			<i class="fa fa-angle-down margin-left-10"></i>
		</div>
		{% if app.user.myUserPage.city != "" %}
		<small class="letter-light elipsis" style="margin-top: -2px;">
			<i class="fa fa-map-marker"></i> {{ app.user.myUserPage.city }}
		</small>
		{% endif %}
	</a>

</div>

{% if socket_enabled == "false" %}
	<button class="btn btn-link margin-left-25 margin-top-10 btn-refresh-notif" title="Actualiser les notifications">
		<i class="fa fa-circle-o-notch fa-2x fa-rotate-180"></i>	
	</button>
{% else %}
	<div class="padding-right-50 d-none d-lg-inline"></div>
	<div class="padding-right-5 d-lg-none"></div>
{% endif %}